{
  "formatVersion": "1.1",
  "component": {
    "group": "com.SomeoneThatIDontKnow",
    "module": "DropperSeedCracker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "oupnbhfxonedhkgdd5hibfagmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DropperSeedCracker-1.0.0.jar",
          "url": "DropperSeedCracker-1.0.0.jar",
          "size": 1969,
          "sha512": "5166f6089a22df7360df9de7a2754da9a7dd5f1cebdc05bad93e545f0fe49a85c1bf336cb3b48e576fa63f64286ceab5ea01b0dd78ab2298d91840296cbd7174",
          "sha256": "3d1566fd92808204681e0777fdbf3f6b8019fc308470563ea1f744b85d19a779",
          "sha1": "19a7ebaa52101905f5210e6111872c5d99dbbf37",
          "md5": "d542590f2ad709646b91cc02b6542914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DropperSeedCracker-1.0.0.jar",
          "url": "DropperSeedCracker-1.0.0.jar",
          "size": 1969,
          "sha512": "5166f6089a22df7360df9de7a2754da9a7dd5f1cebdc05bad93e545f0fe49a85c1bf336cb3b48e576fa63f64286ceab5ea01b0dd78ab2298d91840296cbd7174",
          "sha256": "3d1566fd92808204681e0777fdbf3f6b8019fc308470563ea1f744b85d19a779",
          "sha1": "19a7ebaa52101905f5210e6111872c5d99dbbf37",
          "md5": "d542590f2ad709646b91cc02b6542914"
        }
      ]
    }
  ]
}
