{
  "formatVersion": "1.1",
  "component": {
    "group": "com.SomeoneThatIDontKnow",
    "module": "DropperSeedCracker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "j4zeea5wg5afbervbvxsnft62a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DropperSeedCracker-1.0.0.jar",
          "url": "DropperSeedCracker-1.0.0.jar",
          "size": 1963,
          "sha512": "4e3b8577dd954921e8b7633e46991cb3a6adb8f728cce3c5b3c449aa430e20c0268d8fd784e6e1a2dc53858737b0ca6b7e67cfe2fac8abff8f08865de58d8b2b",
          "sha256": "1d63d22aa6bb3a21722e3c2a4408ce4b4862a2249df0a21b806911ac26cbaae0",
          "sha1": "15576533b09ad7e41099485316d87521a4dc4591",
          "md5": "e1cf4d6b5494b89ffc72b4ec584b9931"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DropperSeedCracker-1.0.0.jar",
          "url": "DropperSeedCracker-1.0.0.jar",
          "size": 1963,
          "sha512": "4e3b8577dd954921e8b7633e46991cb3a6adb8f728cce3c5b3c449aa430e20c0268d8fd784e6e1a2dc53858737b0ca6b7e67cfe2fac8abff8f08865de58d8b2b",
          "sha256": "1d63d22aa6bb3a21722e3c2a4408ce4b4862a2249df0a21b806911ac26cbaae0",
          "sha1": "15576533b09ad7e41099485316d87521a4dc4591",
          "md5": "e1cf4d6b5494b89ffc72b4ec584b9931"
        }
      ]
    }
  ]
}
